#compiled on Mon Aug 11 09:39:09 CDT 2014

#shell/oh_my_zsh.zsh
# Path to your oh-my-zsh configuration.
ZSH=$HOME/.oh-my-zsh

# Set name of the theme to load.
# Look in ~/.oh-my-zsh/themes/
# Optionally, if you set this to "random", it'll load a random theme each
# time that oh-my-zsh is loaded.
ZSH_THEME="robbyrussell"

# Example aliases
# alias zshconfig="mate ~/.zshrc"
# alias ohmyzsh="mate ~/.oh-my-zsh"

# Set to this to use case-sensitive completion
# CASE_SENSITIVE="true"

# Uncomment this to disable bi-weekly auto-update checks
# DISABLE_AUTO_UPDATE="true"

# Uncomment to change how often before auto-updates occur? (in days)
# export UPDATE_ZSH_DAYS=13

# Uncomment following line if you want to disable colors in ls
# DISABLE_LS_COLORS="true"

# Uncomment following line if you want to disable autosetting terminal title.
# DISABLE_AUTO_TITLE="true"

# Uncomment following line if you want to disable command autocorrection
# DISABLE_CORRECTION="true"

# Uncomment following line if you want red dots to be displayed while waiting for completion
# COMPLETION_WAITING_DOTS="true"

# Uncomment following line if you want to disable marking untracked files under
# VCS as dirty. This makes repository status check for large repositories much,
# much faster.
# DISABLE_UNTRACKED_FILES_DIRTY="true"

# Uncomment following line if you want to  shown in the command execution time stamp 
# in the history command output. The optional three formats: "mm/dd/yyyy"|"dd.mm.yyyy"|
# yyyy-mm-dd
# HIST_STAMPS="mm/dd/yyyy"

# Which plugins would you like to load? (plugins can be found in ~/.oh-my-zsh/plugins/*)
# Custom plugins may be added to ~/.oh-my-zsh/custom/plugins/
# Example format: plugins=(rails git textmate ruby lighthouse)
plugins=(git django heroku history history-substring-search jump)

source $ZSH/oh-my-zsh.sh

# User configuration
# export MANPATH="/usr/local/man:$MANPATH"

# # Preferred editor for local and remote sessions
# if [[ -n $SSH_CONNECTION ]]; then
#   export EDITOR='vim'
# else
#   export EDITOR='mvim'
# fi

# Compilation flags
# export ARCHFLAGS="-arch x86_64"

# ssh
# export SSH_KEY_PATH="~/.ssh/dsa_id"


#shell/options.zsh
# Lines configured by zsh-newuser-install
HISTFILE=~/.histfile
HISTSIZE=10000
SAVEHIST=10000
bindkey -e
# End of lines configured by zsh-newuser-install
# The following lines were added by compinstall
zstyle :compinstall filename '/Users/SchiBr01/.zshrc'

autoload -Uz compinit
compinit
# End of lines added by compinstall

#shell/zshhelp.zsh
# Homebrew recommends to put this in the zshrc.
# And I trust homebrew.
unalias run-help
autoload run-help
HELPDIR=/usr/local/share/zsh/helpfiles


#shell/alias.sh
# Pipe my public key to my clipboard.
alias pubkey="more ~/.ssh/id_rsa.pub | pbcopy | echo '=> Public key copied to pasteboard.'"

#serve from local directory
alias serve="python -m SimpleHTTPServer"

alias ack="ack --color"
#shell/env.sh
# Only set this if we haven't set $EDITOR up somewhere else previously.
if [[ "$EDITOR" == "" ]] ; then
  # Use sublime for my editor.
  export EDITOR='vim'
fi

# No permissions, don't bother stealing.
export HOMEBREW_GITHUB_API_TOKEN=ca5f5b692f0bc0dad5e8e16e2e271c654204868b 

export GDAL_DRIVER_PATH=/usr/local/lib/gdalplugins

export DISABLE_KEYERROR=1

#shell/functions.sh

# gem install terminal-notifier
# more info at https://github.com/alloy/terminal-notifier
notify(){
	if [ -z $1 ]; then
		MESSAGE="Done with Task"
	else
		MESSAGE="$@"
	fi
	terminal-notifier -message "$MESSAGE" -sound default
}

shuffle() { 
    awk 'BEGIN{srand();} {printf "%06d %s\n", rand()*1000000, $0;}' | sort -n | cut -c8-
}

jl() { jq '.' $1 -C | less }


#shell/path.sh
export GOPATH=$HOME/go

PATH="/usr/local/opt/coreutils/libexec/gnubin:$PATH" #coreutils w/o g prefix
PATH="/usr/local/opt/ruby/bin:$PATH" #gem-installed executables
PATH="/usr/local/Cellar/go/1.2.1/libexec/bin:$PATH" # GOROOT-based install
PATH="$GOPATH/bin:$PATH"
PATH="/Applications/Postgres.app/Contents/Versions/9.3/bin:$PATH" #Postgres.app path
PATH="$HOME/bin:$PATH"
PATH="/usr/local/bin:$PATH" #homebrew path
export PATH

MANPATH="/usr/local/opt/coreutils/libexec/gnuman:$MANPATH"
export MANPATH

PYTHONPATH=/usr/local/lib/python2.7/site-packages:$PYTHONPATH
PYTHONPATH=/usr/local/lib/python:$PYTHONPATH
export PYTHONPATH




#shell/to.sh
# to - v1.4.4
# Bookmark locations in bash
#
# Copyright (C) 2013 Mara Kim
#
# This program is free software: you can redistribute it and/or modify it under
# the terms of the GNU General Public License as published by the Free Software
# Foundation, either version 3 of the License, or (at your option) any later
# version.
#
# This program is distributed in the hope that it will be useful, but WITHOUT
# ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
# FOR A PARTICULAR PURPOSE. See the GNU General Public License for more
# details.
#
# You should have received a copy of the GNU General Public License along with
# this program. If not, see http://www.gnu.org/licenses/.


### SETTINGS ###

if [ -z "$TO_BOOKMARK_DIR" ]
then
    TO_BOOKMARK_DIR=~/.bookmarks
fi

### MAIN ###
to() {
    # read arguments
    local option
    local input
    local state
    for arg in "$@"
    do
        if [ "$state" = "input" ]
        then
            input+=("$arg")
        elif [ "$arg" = "-h" -o "$arg" = "--help" ]
        then
            \printf 'Usage: to [OPTION] [BOOKMARK] [DEST]
Set the current working directory to a saved bookmark or subdirectory,
or create such a bookmark.
To view bookmarks, execute with no parameters
Options
  -b	Add a new bookmark (overwrites any current bookmark)
  -r	Remove bookmark
  -p	Print bookmark path
  -h	Show help
'
            return 0
        elif [ "$arg" = "--" ]
        then
            state="input"
        elif [ -z "${arg/-*/}" ]
        then
            if [ ! "$option" ]
            then
                option="$arg"
            else
                \printf 'Ignored option: %q\n' "$arg"
            fi
        else
            input+=("$arg")
        fi
    done

    # create empty bookmarks folder if it does not exist
    if [ ! -d "$TO_BOOKMARK_DIR" ]
    then
        \mkdir -pv -- "$TO_BOOKMARK_DIR"
    fi

    if [ -z "$option" -a "${input[*]}" = "" ]
    then
        # show bookmarks
        tree --noreport -C "$TO_BOOKMARK_DIR" | tail -n+2
        return 0
    elif [ "$option" = "-p" ]
    then
        # print path of bookmarks
        local good="good"
        local response
        for i in "${input[@]}"
        do
            if [ "$i" ]
            then
                response+=( "$(\readlink -f -- "$TO_BOOKMARK_DIR/$i")" )
                if [ $? != 0 ]
                then
                    good="bad"
                fi
            fi
        done
        \printf '%q ' "${response[@]}"
        \printf '\n'
        if [ "$good" != "good" ]
        then
            return 1
        else
            return 0
        fi
    elif [ "$option" = "-b" ]
    then
        if [ "$ZSH_VERSION" ]
        then
            local bound=2
        else
            local bound=1
        fi
        # get target
        if [ "${#input[@]}" -gt "$bound" ]
        then
            local end="${#input[@]}-1"
            if [ "$ZSH_VERSION" ]
            then
                local target="${input[-1]}"
            else
                local target="${input[$end]}"
            fi
            if [ -d "$target" ]
            then
                local target="$(\readlink -e -- "$target")"
            else
                \printf '%q does not refer to a directory\n' "$target"
                return 1
            fi
        else
            local target="$PWD"
            local end="${#input[@]}"
        fi
        # add bookmarks
        local good="good"
        if [ "${input[*]}" = "" ]
        then
            local name="$(\basename -- "$PWD")"
            # create link (symbolic force no-dereference Target)
            \ln -sfnT "$target" -- "$TO_BOOKMARK_DIR/$name"
        else
            for i in "${input[@]:0:$end}"
            do
                if [ "$i" ]
                then
                    if [ "$(\basename -- "$i")" != "$i" ]
                    then
                        \printf 'Invalid bookmark name: %q\n' "$i"
                        good="bad"
                        continue
                    else
                        local name="$i"
                    fi
                    if [ "$name" = '/' -o "$name" = '.' -o "$name" = '..' ]
                    then
                        # special cases
                        \printf 'Invalid bookmark name: %q\n' "$name"
                        good="bad"
                        continue
                    fi
                    # create link (symbolic force no-dereference Target)
                    \ln -sfnT "$target" -- "$TO_BOOKMARK_DIR/$name"
                fi
            done
        fi
        if [ "$good" = "good" ]
        then
            return 0
        else
            return 1
        fi
    elif [ "$option" = "-r" ]
    then
        for i in "${input[@]}"
        do
            if [ "$i" ]
            then
                if [ "${i%/}" = "$(_to_path_head "$i")" -a -h "$TO_BOOKMARK_DIR/${i%/}" ]
                then
                    # remove bookmark
                    \rm -- "$TO_BOOKMARK_DIR/${i%/}"
                else
                    \printf 'No bookmark: %q\n' "${i%/}"
                fi
            fi
        done
        return 0
    fi

    # go to bookmark
    for i in "${input[@]}"
    do
        if [ "$i" ]
        then
            if [ -d "$TO_BOOKMARK_DIR/$i" ]
            then
                \cd -P -- "$TO_BOOKMARK_DIR/$i"
            else
                \printf 'Invalid link: %q\n' "$i"
                return 1
            fi
            return 0
        fi
    done
}


### TAB COMPLETION ###

# tab completion generic
# $1 = position of current word (1 is first argument)
# $2-n = words
# Output valid completions
_to() {
    local IFS=$'\0'
    # read arguments
    local word
    local cword
    local option
    local state
    local inputpos
    local input=-1
    local iter=-1
    for arg in "$@"
    do
        if [ -z "$cword" ]
        then
            # get first argument
            cword="$arg"
        elif [ "$state" = "input" ]
        then
            input="$(\expr "$input" + 1)"
        elif [ "$arg" = "-h" -o "$arg" = "--help" ]
        then
            return 0
        elif [ "$arg" = "--" ]
        then
            state="input"
        elif [ -z "${arg/-*/}" ]
        then
            if [ ! "$option" ]
            then
                option="$arg"
            fi
        else
            input="$(\expr "$input" + 1)"
        fi
        if [ "$iter" = "$cword" ]
        then
            word="$arg"
            inputpos="$input"
        fi
        iter="$(\expr "$iter" + 1)"
    done
    if [ -z "$word" ]
    then
        inputpos="$(\expr "$inputpos" + 1)"
    fi

    # create empty bookmarks file if it does not exist
    if [ ! -e "$TO_BOOKMARK_DIR" ]
    then
        \mkdir -pv -- "$TO_BOOKMARK_DIR"
    fi

    # clean word
    word="$(\eval '\printf' '%b' "$word" 2> /dev/null)"
    local stat="$?"
    if [ "$stat" != 0 ]
    then
        return 1
    fi

    # build reply
    local compreply
    if [ "$option" = "-b" ]
    then
        if [ "$inputpos" -ge 1 ]
        then
            # add current directory
            compreply+=("$(\basename -- "$PWD" )")
            # get bookmarks
            local bookmarks
            while \read -r -d '' bookmark
            do
                bookmarks+=( "$bookmark" )
            done < <(\find "$TO_BOOKMARK_DIR" -mindepth 1 -maxdepth 1 -type l -printf '%f\0')
            compreply+=( "${bookmarks[@]}" )
        fi
        if [ "$inputpos" -ge 2 ]
        then
            # normal file completion
            word="${word/#-/./-}"
            compreply+=( $(\find "$(\dirname -- "${word}0")" -mindepth 1 -maxdepth 1 -type d -printf '%p/\0' 2> /dev/null) )
        fi
    elif [ "$option" = "-r" ]
    then
        # get bookmarks
        local bookmarks
        while \read -r -d '' bookmark
        do
            bookmarks+=($bookmark)
        done < <(\find "$TO_BOOKMARK_DIR" -mindepth 1 -maxdepth 1 -type l -printf '%f\0')
        compreply+=( "${bookmarks[@]}" )
    else
        # get subdirs
        local subdirs
        while \read -r -d '' file
        do
            subdirs+=($file)
        done < <(\find "$(\dirname -- "$(\readlink -f -- "$TO_BOOKMARK_DIR/${word}0" || \printf '/dev/null' )")" -mindepth 1 -maxdepth 1 -type d -print0 2> /dev/null)
        local pattern="$(\readlink -f -- "$TO_BOOKMARK_DIR/$(_to_path_head "$word")")"
        local replace="$(_to_path_head "$word")"
        subdirs=( "${subdirs[@]/%//}" )
        subdirs=( "${subdirs[@]/#$pattern/$replace}" )
        compreply+=( "${subdirs[@]}" )

        # get subfiles
        local subfiles
        if [ "$option" = "-p" ]
        then
            while \read -r -d '' file
            do
                subfiles+=($file)
            done < <(\find "$(\dirname -- "$(\readlink -f -- "$TO_BOOKMARK_DIR/${word}0" || \printf '/dev/null' )")" -mindepth 1 -maxdepth 1 -type f -print0 2> /dev/null)
            subfiles=( "${subfiles[@]/#$pattern/$replace}" )
        fi
        compreply+=( "${subfiles[@]}" )

        # get bookmarks (with slash)
        local bookmarks
        while \read -r -d '' bookmark
        do
            bookmarks+=($bookmark)
        done < <(\find "$TO_BOOKMARK_DIR" -mindepth 1 -maxdepth 1 -type l -printf '%f/\0')
        compreply+=( "${bookmarks[@]}" )
    fi

    # generate reply 
    local filter
    for completion in "${compreply[@]}"
    do
        if [ -z "${completion/#$word*}" -a "${completion/#$word}" ]
        then
            filter+=("$completion")
        fi
    done
    COMPREPLY=( "${filter[@]}" )
}

# teleport alias
alias tp="to -p"

# tab completion bash
_to_bash() {
    # call generic tab completion function
    _to "$COMP_CWORD" "${COMP_WORDS[@]}"
}

_tp_bash() {
    COMP_CWORD="$(expr $COMP_CWORD + 1)"
    # call generic tab completion function
    _to "$COMP_CWORD" -p "${COMP_WORDS[@]}"
}

# tab completion zsh
_to_zsh() {
    # call generic tab completion function
    _to "$COMP_CWORD" "${COMP_WORDS[@]}"
    COMPREPLY=( "${(q)COMPREPLY[@]}" )
}

_tp_zsh() {
    COMP_CWORD="$(expr $COMP_CWORD + 1)"
    # call generic tab completion function
    _to "$COMP_CWORD" -p "${COMP_WORDS[@]}"
    COMPREPLY=( "${(q)COMPREPLY[@]}" )
}


# setup tab completion
if [ "$ZSH_VERSION" ]
then
    \autoload -U +X bashcompinit && \bashcompinit
    \complete -o nospace -F _to_zsh to
    \complete -o nospace -F _tp_zsh tp
else
    \complete -o filenames -o nospace -F _to_bash to
    \complete -o filenames -o nospace -F _tp_bash tp
fi


### HELPER FUNCTIONS ###

# get the first part of the path
_to_path_head() {
    if [ "$ZSH_VERSION" ]
    then
        local target
        target=(${(s:/:)${1}})
    else
        local old="$IFS"
        local IFS="/"
        local target=( $1 )
    fi
    local head="$target"
    local prev
    local first
    for part in "${target[@]}"
    do
        if [ "$prev" != "${prev%\\}" ]
        then
            head="$head/$part"
        elif [ -z "$first" ]
        then
            first="no"
        else
            break
        fi
        prev="$part"
    done
    \printf '%b' "$head"
}

